module.exports = [
    {
        id: 'random-uuid1',
        title: 'random-title1',
        description: 'description1',
        completed: true,
        username: 'Expo',
        category: 'random-category1',
      },
      {
        id: 'random-uuid2',
        title: 'random-title2',
        description: 'description2',
        completed: true,
        username: 'Expo',
        category: 'random-category2',
      },
      {
        id: 'random-uuid3',
        title: 'random-title3',
        description: 'description3',
        completed: true,
        username: 'Expo',
        category: 'random-category3',
      },
      {
        id: 'random-uuid4',
        title: 'random-title4',
        description: 'description4',
        completed: true,
        username: 'Expo',
        category: 'random-category4',
      },
      {
        id: 'random-uuid5',
        title: 'random-title5',
        description: 'description5',
        completed: true,
        username: 'Expo',
        category: 'random-category5',
      },
      {
        id: 'random-uuid6',
        title: 'random-title6',
        description: 'description6',
        completed: true,
        username: 'Expo',
        category: 'random-category6',
      },
      {
        id: 'random-uuid7',
        title: 'random-title7',
        description: 'description7',
        completed: true,
        username: 'Expo',
        category: 'random-category7',
      },
      {
        id: 'random-uuid8',
        title: 'random-title8',
        description: 'description8',
        completed: true,
        username: 'Expo',
        category: 'random-category8',
      },
      {
        id: 'random-uuid9',
        title: 'random-title9',
        description: 'description9',
        completed: true,
        username: 'Expo',
        category: 'random-category9',
      },
      {
        id: 'random-uuid10',
        title: 'random-title10',
        description: 'description10',
        completed: true,
        username: 'Expo',
        category: 'random-category10',
      },
]